name: Ubuntu-Server
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #- name: Cleanup Disk
    #  uses: curoky/cleanup-disk-action@v2.0
    
    - uses: fastai/workflows/ssh@master
      with:
        ssh_key: ${{ secrets.SSH_KEY }}
        key_file: id_ecdsa
    - uses: actions/checkout@v2
    - run: echo a #source ubuntu-run.sh
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@master
    - name: Upload Files
      uses: actions/upload-artifact@v1
      with:
         name: files
         path: /file/
